### ISSUE TITLE
Documentation for adding to the list of supported protocols in deep packet inspection?

### ISSUE THREAD

**Issue by kamakazikamikaze** [aouinizied/nfstream#11]
Hi there! I'm currently getting started with using this project. Love it so far. Looking forward to experimenting with plugins.

I have some custom protocols in the traffic that I am analyzing. Deep packet inspection is currently recording these as the wrong `application_name` and `category_name`. What is the proper way to define a custom protocol so that an `NFStreamer` instance will properly categorize the traffic? Do I need to use `NFPlugin`, or do I need to modify the [ndpi](https://github.com/aouinizied/nfstream/blob/master/nfstream/ndpi.py) file? Is this documented somewhere that I've overlooked?

Thank you!

**Comment by aouinizied** [comment]
@kamakazikamikaze depending on the protocol you want to classify, there is several options:

* If your protocol could be identified using currently extracted metadata (SNI, HTTP Useragent, DNS, SSH), then a simple parsing plugin  or a postprocessing refining will do the the trick.

* If it is based on some some information that nDPI stores in its structures, then you can create your plugin and access these structures.

* If it is a more complex protocol then, you can a plugin to dissect it. 

Provide us with more informations  or an example pcap (if it is possible) in order to better understand your needs.

**Comment by kamakazikamikaze** [comment]
It sounds like using a plugin would be the right way to go, since you mentioned it in each bullet point. I wasn't sure where `nDPI` was executed in the process of analyzing traffic. `NFPlugin` is shown as being between the `NFEntry Cache` and `NFEntry Export Formatting`, so I didn't know if `NFPlugin`s took place before or after `nDPI`.
![image](https://user-images.githubusercontent.com/8862823/79385311-fb06bc80-7f2d-11ea-9ad1-822567078c1f.png)

I cannot share a PCAP, but the vast majority of the data I will be examining will have a predictable source port number, so I can easily check that using a plugin. The rest uses random port numbers with binary data (dumping structures straight into the payload) but I can partially parse payloads for matches.

I will experiment with `NFPlugin` then to get it to work as we need it to. Thanks!

**Comment by aouinizied** [comment]
Yes, sounds OK for me.
Just One note regarding how nfstream works:
Every single feature computed in nfstream is an NFPlugin and you can check it in plugins.py file.
So nDPI is also implemented as a Plugin.

Regarding the order, nfstream process its core plugins, nDPI ones and statistitical when enabled.
AFTER, it calls the user defined plugins.

So just keep in mind that when your plugin will be called, every other feature will be computed already and accessible in NFENtry.

Feel free to reopen if you need some help.

BR;
Zied

**Comment by kamakazikamikaze** [comment]
Ok, I see that for `NFPlugin.on_init`, I need to return 1 (or non-zero) if a packet matches criteria. For example:

```python3
class proprietary_comm(NFPlugin):
    def on_init(self, pkt):
        return any(port for port in (pkt.src_port, pkt.dst_port) if port == 65000)
```

This works correctly. What I need to do now is change the `entry.application_name` and `entry.category_name`. I have tried changing it in `on_update` and `on_expiration`, like so:

```python3
    def on_update(self, pkt, entry):
        entry.application_name = 'Proprietary.CMD'
        entry.category_name = 'Proprietary'

    def on_expire(self, entry):
        entry.application_name = 'Proprietary.CMD'
        entry.category_name = 'Proprietary'
```

Neither of these methods worked. I'm guessing this is the wrong way of setting it. What is the more proper way of setting these values?

**Comment by aouinizied** [comment]
Thank you for reporting this.
I fixed it in last commit. I tested a similar scenario as follows which work.

`class magic_ssl(NFPlugin):
    def on_init(self, pkt):
        return any(port for port in (pkt.src_port, pkt.dst_port) if port == 443)
    def on_expire(self, flow):
        flow.application_name = "magic_ssl.magic_ssl"

flow_streamer = NFStreamer(source=path, plugins=[magic_ssl(volatile=True)])`

Note than in your case, your plugin is a volatile one as its output will be just updating an existing metric.
So, on_init can return whatever you want even a list or a dict.

After that you can access this volatile variable and change it within on_update or on_expire by:
flow.magic_ssl      (flow.plugin_name)

You need rebuild from source in order to have the fix.
I will publish a new version later on Pypi.

BR,
Zied

**Comment by aouinizied** [comment]
Another full example to your scenario:

Let's suppose that you want to detect a proprietary protocol
The protocol signature is as follow:
* dst_port=6666
* The third packet from dst to src has a size equal to 555
* tansport_protocol is UDP

```python
class proprietary_dissector(NFPlugin):
    def on_init(self, pkt):
        my_internal_state = [False, False, False]
        if pkt.dst_port == 6666:
             my_internal_state[0] = True
        if pkt.protocol == 17:
            my_internal_state[1] = True
        return my_internal_state

    def on_update(self, pkt, flow):
        if pkt.direction == 1 and flow.dst2src_packets == 3 and pkt.raw_size == 555:
            flow.proprietary_dissector[3] = True

    def on_expire(self, flow):
        if flow.proprietary_dissector[0] and flow.proprietary_dissector[1] and flow.proprietary_dissector[2]:
            flow.application_name = "proprietary_com.comm"
            flow.category_name = "proprietaryCategory"

flow_streamer = NFStreamer(source=path, plugins=[proprietary_dissector(volatile=True)])`
```

Note that for your previous example, it will work even with previous build if you set your plugin as volatile as the issue was for non-volatile plugins only.
