### ISSUE TITLE
provide an abstract Classifier for Streamer __iter__

### ISSUE THREAD

**Issue by RadionBik** [aouinizied/nfstream#2]
Hello!

This is rather a refactor request.

The code works with nDPI, but if an instance of another classifier is required, there is no transparent way to extend the code. At this point, I could override `__iter__` method of `Streamer` in a child class and include a custom classifier to the code you have, so that I could reuse the same Observer instance and to have information about the point at which nDPI performs classification. But this approach will suffer if smth within `Streamer. __iter__` will be changed. A possible soultion would be an abstract class `Classifier`, where some of the content of current `Streamer` will be relocated, leaving to it only implementation  of the `__iter__` method where the Classifiers fabric will be invoked. In such a way, it will be straight-forward to add different traffic classifiers to the code

For example:
```
class nDPIClassifier(AbstractClassifier):
...
    def consume(pkt_info):
    ...
    ...
    # if classification is ready
    yield export


class Streamer
...
def __iter__(self):
    ndpi = ClassifierFabric(stuff, 'ndpi')
    custom = ClassifierFabric(stuff, 'custom')
    for pkt_info in Observer(source=self.source):
        # zip is a bad idea, this is for the illustration of a joint classifcation
        for ndpi_results, custom_results in  zip(ndpi.consume(pkt_info), custom.consume(pkt_info)):
            yield ndpi_results, custom_results
```

The code just  illustrates idea of hiding the implementation of the nDPI classifier within the `__iter__` .

**Comment by aouinizied** [comment]
Hi Radion,

I agree with you on that point. However I need to understand possible use cases behind it.
The reason why I didn't implement it is that I was thinking about nDPI as the most reliable ground truth generator **[1]** and flexible as you can add custom matching rules, custom categories, etc.

So nDPI is more our ground-truth-genrator and we need to implement easy extensions to it (protocol files and so on.)

Now the use case I see for such Classifier abstraction layer is when for example you trained a machine learning model, and you want to evaluate it on real data.

So, let's say that your model take a set of 5 features (first 5 packets size as example). You can implement easily your 5 features as user_metrics within the current implementation. Once a flow is exported on your app side, you perform a model.predict(your_features).
The problem is in such case, you are performing a post-mortem evaluation. You cannot use nfstream in a way that once your model detects something, you block the flow or this king of stuff.

So to perform early classification and action, we indeed need an abstraction layer and we need to  implement a field in flow class, let's say custom_export.

class MagicClassifier():
     def __init__(self):
          initialize your stuff
    def update(flow, pkt_info)
         update whatever you want
    def terminate(flow, pkt_info)
        terminate stuff (example ndpi_give_up or set flow.custom_export to True)

Streamer need to be modified in order to call custom classifiers at the right order/level and flow must be watched in order to yield export if custom_export is True.
What do you think about it? 


**[1]** http://people.ac.upc.edu/pbarlet/papers/ground-truth.pam2014.pdf

**Comment by RadionBik** [comment]
Hi! 

I suggest you to take a look at Tomasz Bujlow's PhD thesis, he in details compared various DPIs. That is one of the reasons I used nDPI as the ground-truth provider in https://github.com/RadionBik/ML-based-network-traffic-classifier

I am actually planning to insert an ML classifier that will provide predictions if nDPI fails (e.g. when eSNI is activated). I think this a good research direction, so we can do that together,  since IMHO there are no available hybrid classifiers.

It is difficult to say about exact abstraction, since ML classifiers have to perform some custom logic (e.g. parse a TLS handshake), although it is already implemented in nDPI, but there are no bindings. My idea was to monitor point at which nDPI triggers classification, and when it predicts the Unknown label, we call an ML classifier basing on the packets we have received from the Observer. Therefore, an abstraction that can receive signals from the outputs of other classifiers (or nDPI at least) and the Observer is needed.


Also, we can utilize nDPI as a constant source of flow labels for the online training when it is sure about the predictions.  

As for the current extension mechanism, is it possible to extract the packet number  from a flow? For example, if need to process a complete handshake, rather than  its distinct packets.

Also, current implementation of Streamer produces predictions for a batch of accumulated flows,  since it is waiting for a packet to decide whether the timer has expired. I think something async will be required in future releases. In addition, I would add a check for TCP-END segment, if we see it, then the  flow MUST be classified.

**Comment by aouinizied** [comment]
https://github.com/aouinizied/nfstream/commit/ba11caeea78b903cbf7f2c8cdf07fdda7e40ec76
I implemented an abstraction for Classifier. Have a look at it.

**Comment by aouinizied** [comment]
ndpi is default (can be unset) and you can add a list of Classifiers that Inherit from NFStreamClassifier Class.
custom_export field to Flow class. There if Streamer see it as set to True, he knows that it must be exported.
Fin flag will be added too.
Packet_information also will have 'content' field which will pint to raw packet, in that case you can parse it with you favourite lib on Classifier side.

**Comment by aouinizied** [comment]
Yes just look at packets counters in flow. 
For example your extension check flow.src_todst_pkts + flow.src_todst_pkts before doing something.
However you must know that this counters includes packet you are processing in your extension.

**Comment by aouinizied** [comment]
Fixed and examples provided in documentation.
https://github.com/aouinizied/nfstream/releases/tag/v0.5.0
