### ISSUE TITLE
account_ip_padding_size has no effect

### ISSUE THREAD

**Issue by RadionBik** [aouinizied/nfstream#20]
**Describe the bug**
NFpacket's attribute `ip_size_from_header` has the same value as `ip_size`, although pcap analysis via Wireshark shows proper values.

![image](https://user-images.githubusercontent.com/19979628/87809721-86148d00-c864-11ea-94a6-c52eebb0e5b9.png)

**To Reproduce**
Parse possibly any .pcap file with truncated payload. I tested both account_ip_padding_size options. 

**Additional context**
Tested with release v5.1.6

possible source of the problem must somewhere here:
https://github.com/aouinizied/nfstream/blob/ba153879b2ba61d797ecbeec5cc84abb0eb3f895/nfstream/observer_cc.c#L647

If needed, I can provide with the pcap trace.

**Comment by aouinizied** [comment]
@RadionBik thanks for the report. Do you have any pcap trace in order to reproduce? (small one with few packets just to check their headers)

**Comment by RadionBik** [comment]
Take a look at this one, should be sufficient for testing.
[truncated_test.zip](https://github.com/aouinizied/nfstream/files/4939038/truncated_test.zip)

**Comment by aouinizied** [comment]
I will illustrate the usage of account_ip_padding_size by a practical example:

* On a TCP packet level, the minimum total size must be equal to 64 bytes (it is not possible to make a valid TCP packet smaller than this size). If a TCP packet is sent without data bytes, its headers will sum up to 40 bytes (i.e., 20 for the TCP layer and 20 for the IP layer). As a result, the packet is zero-padded out to 46 bytes before the Ethernet FCS is attached (e.g., 12
bytes of Ethernet header and 2 bytes of Ethernet FCS).

* With this in mind, some measurement tools include the padded part in the calculation (e.g., 46 bytes), and other tools ignore it (e.g., 40 bytes).

The idea behind account_ip_padding_size parameter is to give the user the choice to set this measurement choice.

Now when I get back to your example, it's normal to have no effect if there is no padding in the packet. Another point is that the encapsulation of your pcap is IP raw packet. Meaning that there is no layer 2 and you can observe that with raw_bytes always equal to ip_bytes.

Here an example where you can observe such an effect:

```python
NFStreamer(source="pcaps/google_ssl.pcap", account_ip_padding_size=True).to_pandas()["bidirectional_ip_bytes"]
NFStreamer(source="pcaps/google_ssl.pcap", account_ip_padding_size=False).to_pandas()["bidirectional_ip_bytes"]
```

You will observe 20 bytes difference due to padding.

Zied

**Comment by RadionBik** [comment]
Thank you for the explanation, I understand it differs from what I thought it does. As for the Length parameter that is seen on the wireshark screen above, it appears to be extracted from the IP raw packet layer. Do you think it is possible to include this parameter as an (optional) attribute of NFPacket?

**Comment by aouinizied** [comment]
@RadionBik v5.2.0 introduce API changes as we dropped account_ip_padding_size option.

* Now, you both raw, IP, transport and payload sizes are computed from headers. Consequently, you can use truncated traces without issues for statistical features computation (I tested on CAIDA and MAWI).

If you want to account zeros (account_ip_padding_size), you can use len(pkt.ip_packet) which report the real IP captured size in a user defined plugin.

Enjoy :)
